version: '2.1'
services:
    luigid:
      image: axiom/docker-luigi
      container_name: awesome_ml_luigid
      ports:
        - "8082:8082"

      command: luigid
      networks:
        dev:
          aliases: [luigid]

    dask-scheduler:
      build:
        context: .
        dockerfile: Dockerfile
      image: drtools/drtools:latest
      command: dask-scheduler
      container_name: awesome_ml_dask-scheduler
      networks:
        dev:
          aliases: [dask-scheduler]
      ports:
        - "8787:8787"
        - "8788:8788"


    dask-worker:
      build:
        context: .
        dockerfile: Dockerfile
      image: drtools/awesome_ml:latest
      depends_on:
        - dask-scheduler
      volumes:
        - ./root_dir:/home/drtools/awesome_ml/root_dir
      ports:
        - "8789:8789"
      networks:
        - dev
      command: >
                 dask-worker dask-scheduler:8786
                 --nprocs 8
                 --memory-limit 0.5

    controller:
      build:
        context: .
        dockerfile: Dockerfile
      image: drtools/awesome_ml:latest
      user: root
      depends_on:
        - dask-scheduler
        - dask-worker
        - luigid
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./root_dir:/home/drtools/awesome_ml/root_dir
      networks:
        - dev
      environment:
        - DRTOOLS_SETTINGS_MODULE=awesome_ml.settings.default
        - HOST_ROOT=$PWD/root_dir
        - CONTROLLER=1
      entrypoint: ['luigi', '--module', 'awesome_ml.task']

# Uncomment this section and set SMTP_PASS var to enable luigi notifications
#    smtp-relay:
#      image: juanluisbaptiste/postfix:latest
#      networks:
#       dev:
#          aliases: [smtp-relay]
#      environment:
#        - SMTP_SERVER=mail.privateemail.com
#        - SMTP_USERNAME=luigi@datarevenue.de
#        - SMTP_PASSWORD=$SMTP_PASS
#        - SERVER_HOSTNAME=datarevenue.de

networks:
  dev:
    external: false