version: 2
jobs:
  build:
    docker:
      - image: drtools/drtools:latest
        auth:
          username: $DOCKERHUB_UN
          password: $DOCKERHUB_PW
    environment:
      DRTOOLS_SETTINGS_MODULE: awesome_ml.settings.default
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install package locally
          command: pip install -e .

      - run:
          name: Run unitests
          command: py.test awesome_ml/tests

      # TODO move this into the image
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      # TODO move this into the image
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

      - run:
          name: Build image
          command: docker build -t drtools/awesome_ml .

      - run:
          name: Start services
          command: docker-compose -f docker-compose.yml up -d

      - run:
          name: Run integration tests
          command: TEST_INTEGRATION=true py.test awesome_ml/tests/test_integration.py
