apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prefect-deployment-cr
rules:
- apiGroups: ["machinelearning.seldon.io"]
  #
  # at the HTTP level, the name of the resource for accessing Deployment
  # objects is "deployments"
  resources: ["seldondeployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]