apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prefect-deployment
subjects:
- kind: ServiceAccount
  name: prefect-deployment-sa
  namespace: prefect
roleRef:
  kind: ClusterRole
  name: prefect-deployment-cr
  apiGroup: rbac.authorization.k8s.io