# http://distributed.readthedocs.io/en/latest/configuration.html
logging:
    distributed: info
    distributed.client: warning
    bokeh: critical

worker-memory-target: 0.60  # target fraction to stay below
worker-memory-spill: 0.70  # fraction at which we spill to disk
worker-memory-pause: False  # fraction at which we pause worker threads
worker-memory-terminate: 0.95  # fraction at which we terminate the worker