# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  model-deployment:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:        
          python-version: 3.8
      
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install prefect
        
      - name: Set prefect server
        run: | 
            prefect backend server && \
            echo "PREFECT__CLOUD__API=http://prefect-server-apollo.prefect:4200/graphql/" >> $GITHUB_ENV

      - name: Run deployment flow
        run: |
          echo Running deployment flow
          prefect run flow --name model-deployment-pipeline --project mlops-demo
